version: '3.8'
services:
  agent-service:
    build:
      context: .
      dockerfile: Dockerfile.agents
    container_name: monitoring-agents
    volumes:
      - ./agents:/app/agents
      - ./models:/app/models
      - ./api_logs.json:/app/api_logs.json
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - EMAIL_ENDPOINT=${EMAIL_ENDPOINT}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - elk_network
    restart: unless-stopped

networks:
  elk_network:
    external: true
    name: elk_network