version: '3.8'
services:
  agent-service:
    build:
      context: .
      dockerfile: Dockerfile.agents
    container_name: monitoring-agents
    volumes:
      - ./agents:/app/agents
      - ./models:/app/models
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - EMAIL_ENDPOINT=${EMAIL_ENDPOINT}
    networks:
      - default

networks:
  default:
    external: true
    name: barclaysssssssss_default